[phases.setup]
aptPkgs = ['curl']
cmds = [
    'curl -fsSL https://deb.nodesource.com/setup_18.x | bash -',
    'apt-get install -y nodejs'
]

[phases.install]
cmds = [
    'cd backend',
    'npm install'
]

[phases.build]
cmds = ['cd backend && npm run build']

[start]
cmd = 'cd backend && npm start' 